[package]
name = "a2600_hw_dbg"
version = "0.1.0"
edition = "2021"

[dependencies]
a2600_emu = { path = "../emu" }
clap = "4.5.16"
reedline = "0.32.0"
clap-repl = "0.3.0"
num-traits = "0.2.19"
homedir = "0.3.3"

[dev-dependencies]
test-case = "3.3.1"
