[package]
name = "rustella"
version = "0.1.0"
authors = ["unrenormalizable <unrenormalizable@gmain.com>"]
edition = "2021"

[dependencies]
bitflags = "1.2.1"
num-traits = "0.2"

[dev-dependencies]
test-case = "3.3.1"
